apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.15
appVersion: "7e25e40"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
