apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.12
appVersion: "fdb1339"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
