apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.38
appVersion: "378a5dc"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
