apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.31
appVersion: "c45a8b3"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
