apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.29
appVersion: "f80efda"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
