apiVersion: v2
name: testops-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.9
appVersion: "f039e2d"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
