apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.33
appVersion: "a5d6150"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
