apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.18
appVersion: "32c01d0"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
