apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.35
appVersion: "fa8c3c1"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
