apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.22
appVersion: "1f27846"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
