apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.36
appVersion: "c5fd0fc"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
