apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.41
appVersion: "8ec9145"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
