apiVersion: v2
name: team9-consumer
description: Consumer service for TestOps platform
type: application
version: 1.1.32
appVersion: "d239c5a"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
