apiVersion: v2
name: team9-notification
description: Notification service for TestOps platform
type: application
version: 0.1.2
appVersion: "1f27846"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
