apiVersion: v2
name: team9-notification
description: Notification service for TestOps platform
type: application
version: 0.1.12
appVersion: "f6df5e5"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
