apiVersion: v2
name: team9-notification
description: Notification service for TestOps platform
type: application
version: 0.1.3
appVersion: "d424a12"
maintainers:
  - name: Duc Truong
    email: thduc.dev@gmail.com
