apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-testops.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-testops.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-testops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-testops.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
