apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-testops.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ai-testops.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-testops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-testops.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.enabled }}
          {{- with .Values.probes.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            {{- if .httpGet }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}

          {{- with .Values.probes.readinessProbe }}
          {{- if .enabled }}
          readinessProbe:
            {{- if .httpGet }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            {{- end }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            failureThreshold: {{ .failureThreshold }}
            successThreshold: {{ .successThreshold }}
          {{- end }}
          {{- end }}

          {{- with .Values.probes.startupProbe }}
          {{- if .enabled }}
          startupProbe:
            {{- if .httpGet }}
            httpGet:
              path: {{ .httpGet.path }}
              port: {{ .httpGet.port }}
            {{- end }}
            failureThreshold: {{ .failureThreshold }}
            periodSeconds: {{ .periodSeconds }}
          {{- end }}
          {{- end }}
          {{- end }}
