apiVersion: v1
entries:
  team9-consumer:
  - apiVersion: v2
    appVersion: 378a5dc
    created: "2025-12-28T17:13:11.091460491Z"
    description: Consumer service for TestOps platform
    digest: 6cd9c13a0b1afd71d893b56361990c1e0e09a042f981f67c71c6224bbc41cebe
    maintainers:
    - email: thduc.dev@gmail.com
      name: Duc Truong
    name: team9-consumer
    type: application
    urls:
    - https://CSU-ITMO-2025-2.github.io/team9-testops/charts/team9-consumer-1.1.38.tgz
    version: 1.1.38
  - apiVersion: v2
    appVersion: e1c4e8b
    created: "2025-12-28T17:13:11.091084491Z"
    description: Consumer service for TestOps platform
    digest: 3b385e1199d5fccda07579dd1cbda75e905cc2cacafafc993759b3ad47a27270
    maintainers:
    - email: thduc.dev@gmail.com
      name: Duc Truong
    name: team9-consumer
    type: application
    urls:
    - https://CSU-ITMO-2025-2.github.io/team9-testops/charts/team9-consumer-1.1.37.tgz
    version: 1.1.37
  - apiVersion: v2
    appVersion: c5fd0fc
    created: "2025-12-28T17:13:11.090710704Z"
    description: Consumer service for TestOps platform
    digest: 57a5833419fe354538d74e64dd54f9fbb2b08cccf630fb441f94bb8e75dbae67
    maintainers:
    - email: thduc.dev@gmail.com
      name: Duc Truong
    name: team9-consumer
    type: application
    urls:
    - https://CSU-ITMO-2025-2.github.io/team9-testops/charts/team9-consumer-1.1.36.tgz
    version: 1.1.36
generated: "2025-12-28T17:13:11.090193871Z"
