apiVersion: v1
entries:
  team9-consumer:
  - apiVersion: v2
    appVersion: c5fd0fc
    created: "2025-12-28T16:48:18.692520326Z"
    description: Consumer service for TestOps platform
    digest: 57a5833419fe354538d74e64dd54f9fbb2b08cccf630fb441f94bb8e75dbae67
    maintainers:
    - email: thduc.dev@gmail.com
      name: Duc Truong
    name: team9-consumer
    type: application
    urls:
    - https://CSU-ITMO-2025-2.github.io/team9-testops/charts/team9-consumer-1.1.36.tgz
    version: 1.1.36
generated: "2025-12-28T16:48:18.691961471Z"
