{{- if .Values.global.postgres.external }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-db-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - remoteRef:
        key: kv/data/team9/postgres
        property: password
      secretKey: POSTGRES_PASSWORD
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-secret
    template:
      metadata:
        name: postgres-secret
        namespace: {{ .Values.global.namespace }}
        labels:
          {{- include "ai-testops.labels" . | nindent 10 }}
      type: Opaque
      data:
        POSTGRES_USER: {{ .Values.global.postgres.external.username | b64enc | quote }}
{{- end }}
