{{- if .Values.global.postgres.external }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-db-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - remoteRef:
        key: kv/data/team9/postgres
        property: password
      secretKey: POSTGRES_PASSWORD
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgres-secret
    template:
      metadata:
        name: postgres-secret
        namespace: {{ .Values.global.namespace }}
        labels:
          {{- include "ai-testops.labels" . | nindent 10 }}
      type: Opaque
      data:
        POSTGRES_USER: {{ .Values.global.postgres.external.username | b64enc | quote }}
        POSTGRES_PASSWORD: {{ .Values.global.postgres.external.password | b64enc | quote }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-django-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - remoteRef:
        key: kv/data/team9/django
        property: secret_key
      secretKey: SECRET_KEY
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: django-secret
    template:
      metadata:
        name: django-secret
        namespace: {{ .Values.global.namespace }}
        labels:
          {{- include "ai-testops.labels" . | nindent 10 }}
      type: Opaque
---
{{- if .Values.global.secrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-api-keys-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    - remoteRef:
        key: kv/data/team9/api-keys
        property: gemini_api_key
      secretKey: GEMINI_API_KEY
    - remoteRef:
        key: kv/data/team9/api-keys
        property: google_oauth2_key
      secretKey: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
    - remoteRef:
        key: kv/data/team9/api-keys
        property: google_oauth2_secret
      secretKey: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
    - remoteRef:
        key: kv/data/team9/api-keys
        property: grafana_cloud_api_key
      secretKey: GRAFANA_CLOUD_API_KEY
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: api-keys-secret
    template:
      metadata:
        name: api-keys-secret
        namespace: {{ .Values.global.namespace }}
        labels:
          {{- include "ai-testops.labels" . | nindent 10 }}
      type: Opaque
{{- end }}
