{{- $ns := .Values.global.namespace }}
{{- $labels := include "ai-testops.labels" . }}

{{/* ===================== POSTGRES ===================== */}}
{{- if .Values.global.postgres.external }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-db-secret
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  dataFrom:
    - extract:
        key: kv/data/team9/postgres

  target:
    name: postgres-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
{{ $labels | nindent 10 }}
{{- end }}

{{/* ===================== DJANGO ===================== */}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-django-secret
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  dataFrom:
    - extract:
        key: kv/data/team9/django

  target:
    name: django-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
{{ $labels | nindent 10 }}

{{/* ===================== API KEYS ===================== */}}
{{- if .Values.global.secrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team9-api-keys-secret
  namespace: {{ $ns }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  dataFrom:
    - extract:
        key: kv/data/team9/api-keys

  target:
    name: api-keys-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
{{ $labels | nindent 10 }}
{{- end }}
