{{- if .Values.networkPolicies.enabled }}
{{- if .Values.networkPolicies.denyAllByDefault }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}

{{- if .Values.networkPolicies.allowDjangoToPostgres }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-django-to-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: team9-publisher
    ports:
    - protocol: TCP
      port: 5432
{{- end }}

{{- if .Values.networkPolicies.allowDjangoToKafka }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-django-to-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: team9-publisher
    - podSelector:
        matchLabels:
          app: kafka-topic-init
    ports:
    - protocol: TCP
      port: 9092
{{- end }}

{{- if .Values.networkPolicies.allowConsumerToKafka }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-consumer-to-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: test-execute-consumer
    ports:
    - protocol: TCP
      port: 9092
{{- end }}

{{- if .Values.networkPolicies.allowExternalToDjango }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-django # Allow external traffic to Django app
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: team9-publisher
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8000
{{- end }}

{{- if .Values.networkPolicies.allowKafkaUIToKafka }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-ui-to-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kafka-ui
    ports:
    - protocol: TCP
      port: 9092
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-kafka-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: kafka-ui
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8080
{{- end }}

{{- if .Values.networkPolicies.allowKEDAToKafka }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keda-to-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "testops-postdeploy.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: keda
    ports:
    - protocol: TCP
      port: 9092
{{- end }}
{{- end }}
