# Default values for team9-publisher

namespace: team9-ns

# Global image settings
image:
  pullPolicy: Always

# Django Application
djangoApp:
  enabled: true
  name: team9-publisher
  replicaCount: 1
  image:
    repository: vanlahuynhduc/ai-testops
    tag: "2afe793"
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "200m"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

# External dependencies (deployed by testops-infra)
postgres:
  name: postgres
  service:
    port: 5432

kafka:
  name: kafka
  service:
    port: 9092

# Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: team9.kubepractice.ru
      paths:
        - path: /
          pathType: Prefix
          service: team9-publisher
          port: 8000
    - host: team9.kubepractice.ru
      paths:
        - path: /
          pathType: Prefix
          service: team9-publisher
          port: 8000
  tls:
    - secretName: testops-tls
      hosts:
        - team9.kubepractice.ru
    - secretName: team9-kubepractice-tls
      hosts:
        - team9.kubepractice.ru
